SET IDENTITY_INSERT [dbo].[Courses] ON
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (1, 0, N'course_1.svg', N'Fullstack Web Development Course from Scratch', N'Robert Fox', N'$12.50', NULL, N'220', N'94%', N'4.2K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (2, 1, N'course_2.svg', N'HTML, CSS, JavaScript Web Developer', N'Jenny Wilson & Marvin McKinney', N'$15.99', NULL, N'160', N'92%', N'3.1K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (3, 2, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$9.99', N'$44.99', N'160', N'92%', N'3.1K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (4, 3, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$9.99', N'$44.99', N'160', N'92%', N'3.1K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (5, 4, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$9.99', N'$44.99', N'160', N'92%', N'3.1K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (6, 5, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$9.99', N'$44.99', N'160', N'92%', N'3.1K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (7, 6, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$9.99', N'$44.99', N'160', N'92%', N'3.1K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (8, 7, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$9.99', N'$44.99', N'160', N'92%', N'3.1K')
INSERT INTO [dbo].[Courses] ([Id], [IsBestseller], [Image], [Title], [Author], [Price], [DiscountPrice], [Hours], [LikesInProcent], [LikesInNumbers]) VALUES (9, 8, N'course_3.svg', N'The Complete Front-End Web Development Course', N'Albert Flores', N'$9.99', N'$44.99', N'160', N'92%', N'3.1K')
SET IDENTITY_INSERT [dbo].[Courses] OFF
